requirements: relax version bound on "pep517"
The "<0.7.0" bound was added in https://github.com/kivy/python-for-android/commit/9f6d6fcce748be96ed606815aca9294644ac90cc
to fix https://github.com/kivy/python-for-android/issues/1994 :

> The `TestGetSystemPythonExecutable.test_virtualenv` and `TestGetSystemPythonExecutable.test_venv` tests started failing all of a sudden. Error was:
>
> ```
> ModuleNotFoundError: No module named \'pytoml\'\n'
> ```
>
> This ca be reproduced in local via:
>
> ```shell
> pytest tests/test_pythonpackage_basic.py::TestGetSystemPythonExecutable::test_virtualenv
> ```

I think this no longer applies,
`$ pytest tests/test_pythonpackage_basic.py::TestGetSystemPythonExecutable`
runs successfully for me, using latest `pep517==0.13.0`.