:white_check_mark: improve sh mocking reliability
Make sure the mocking also works on setup without cmake or make.
Build dependencies should not be required to run uni tests.
The error was:
```
AttributeError: <module 'sh' from 'venv/lib/python3.11/site-packages/sh.py'> does not have the attribute 'cmake'
```