Fixes Python3.6 and enum34
Module `enum34` should only be installed on Python < 3.4
Fixes host Python3 regression from ecd0bf6, the error was:
```
AttributeError: module 'enum' has no attribute 'IntFlag'
```