Requests runtime permissions list, fixes #1704
Matches the official Android API via, making it possible to request
multiple runtime permissions at once.

Keeps the previous `android.permissions.request_permission()` interface
for compatibility.

Bumps pyjnius to post 1.2.0 release that solves required method
resolution issues. On 1.2.0, the error was:
```
jnius.jnius.JavaException: No methods matching your arguments, available: []
```