:bug: Adds missing requests sub dependencies
The `requests` module has `urllib3`, `chardet` and `idna` as dependencies.
This used to be handled dynamically thanks to the `requests` recipe.
This is a drawback and side effect of #2202.
The on device error was:
```
Imported unittest
loading tests...
running unittest...
unittest result is:
....EE........
======================================================================
ERROR: test_import_module (tests.test_requirements.RequestsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/app/testapps/on_device_unit_tests/build/bdist.android-armeabi-v7a/test_app/tests/mixin.py", line 17, in test_import_module
  File "/home/user/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/.local/share/python-for-android/build/python-installs/bdist_unit_tests_app/requests/__init__.py", line 43, in <module>
ModuleNotFoundError: No module named 'urllib3'

======================================================================
ERROR: test_run_module (tests.test_requirements.RequestsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/app/testapps/on_device_unit_tests/build/bdist.android-armeabi-v7a/test_app/tests/test_requirements.py", line 74, in test_run_module
  File "/home/user/.local/share/python-for-android/build/python-installs/bdist_unit_tests_app/requests/__init__.py", line 43, in <module>
ModuleNotFoundError: No module named 'urllib3'

----------------------------------------------------------------------
Ran 14 tests in 0.591s

FAILED (errors=2)

Ran tests
```
Also sneaked a minor documentation regression fix (bug introduced in #2219).