Bumps netiffaces version & removes from broken list, refs #1539
Only `python2` build fails with:
```
  RAN: /home/user/.local/share/python-for-android/build/other_builds/hostpython2/desktop/hostpython2/native-build/python setup.py build_ext -v

  STDOUT:
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import setuptools
ImportError: No module named setuptools
```