:bug: Fixes pip command on Travis and bumps actions/setup-python
Travis error was:
```
pyenv: pip3.7: command not found
```
Also bumps `actions/setup-python` to latest tag.
Hopefully fixes recent `set-env` and `add-path` commands depreciation.
The error is:
```
Error: Unable to process command
'##[set-env name=pythonLocation;]/opt/hostedtoolcache/Python/3.7.9/x64' successfully.
Error: The `set-env` command is disabled.
Please upgrade to using Environment Files or opt into unsecure command execution by
setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`.
For more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```